config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do
    root "static_pages#home"

    devise_scope :user do
      get "/login", to: "devise/sessions#new", as: "login"
      post "/login", to: "devise/sessions#create"
      get "/register", to: "devise/registrations#new", as: "register"
      delete "/logout", to: "devise/sessions#destroy", as: "logout"
    end
    get "/search", to: "documents#search", as: "search"

    namespace :admin do
      resources :documents, only: %i(index edit update)
      resources :users, only: %i(index edit update) do
        collection do
          get "/export", to: "users#export"
          get "/export_status", to: "users#export_status"
          get "/export_download", to: "users#export_download"
        end
      end
      resources :categories, only: %i(index edit update new create)
      resources :histories, only: :index
    end

    resources :documents, only: %i(create show) do
        resources :comments, only: %i(new create delete)
    end
    resources :comments do
      resources :comments, only: %i(new create delete)
    end
    resources :downloads, only: :show
    resources :categories, only: %i(new create)
    resources :favorites, only: %i(create destroy)
    resources :account_activations, only: :edit
    devise_for :users
    resources :users, only: %i(show) do
      member do
        get :favorites
      end
    end
    authenticate :user, ->(user) { user.admin? } do
      mount Sidekiq::Web, at: "/sidekiq"
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :document
  belongs_to :comment, optional: true, class_name: Comment.name,
    foreign_key: :reply_comment_id
  has_many :reply_comments, class_name: Comment.name,
    foreign_key: :reply_comment_id, dependent: :destroy

  validates :content, presence: true, length: {
    maximum: Settings.comment_max_length
  }

  scope :by_created_at, ->{order created_at: :desc}
  scope :root_comment, ->{where reply_comment_id: nil}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource param_method: :com_params
  before_action :build_comment, only: :create

  def new
    @comment = Comment.new
  end

  def create
    if @comment.save
      flash[:success] = t "success.post_comment"
    else
      flash[:danger] = t "error.post_comment"
    end
    redirect_to request.referer
  end

  def destroy
    if @comment.destroy
      flash[:success] = t "success.delete_comment"
    else
      flash[:danger] = t "error.delete_comment"
    end
    redirect_to request.referer
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @comment.update_attributes com_params
      flash[:success] = t "success.update_comment"
    else
      flash[:danger] = t "error.update_comment"
    end
    redirect_to @comment.document
  end

  private

  def build_comment
    @comment = current_user.comments.build com_params
    if params[:comment_id].present?
      @comment.reply_comment_id = params[:comment_id]
      load_reply_comment params[:comment_id]
      doc_id = @reply_comment.document_id
    else
      doc_id = params[:document_id]
    end
    load_document doc_id
    @comment.document_id = @document.id
  end

  def com_params
    params.require(:comment).permit :content, :comment_id, :document_id
  end

  def load_document doc_id
    @document = Document.find_by id: doc_id
    return if @document

    flash[:danger] = t "error.invalid_doc"
    redirect_to root_url
  end

  def load_reply_comment com_id
    @reply_comment = Comment.find_by id: com_id
    return if @reply_comment

    flash[:danger] = t "error.invalid_comment"
    redirect_to root_url
  end
end

app/views/comments/_comment.html.erb
<li>
  <%= comment.user.fullname %>
  <div id=<%= "content_"+comment.id.to_s %> class="content-wrapper">
    <%= comment.content %>
  </div>
  <small><%= time_ago_in_words(comment.created_at) %></small>
  <a data-commentID=<%= comment.id %> class="reply"><i class="fa fa-reply"></i></a>
  <% if can? :delete, comment %>
    <%= link_to comment, method: :delete, data: {confirm: t("cfm")} do %>
      <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  <% end %>
  <% if can? :update, comment %>
    <%= link_to edit_comment_path(comment), remote: true do %>
      <i class="fas fa-edit"></i>
    <% end %>
  <% end %>
  <%= form_for [comment, Comment.new], html: {id: "reply_comment" + comment.id.to_s,class: "reply_comment"} do |f| %>
    <%= f.text_area :content, placeholder: t("reply_placeholder") %><br/>
    <%= f.submit t("reply") %>
  <% end %>
  <ul>
    <%= render comment.reply_comments %>
  </ul>
</li>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.text_area :content, value: @comment.content %><br/>
  <%= f.submit t("reply") %>
<% end %>

app/views/comments/edit.js.erb
$('<%= "#content_"+@comment.id.to_s %>').html('<%= j render "comments/form", comment: @comment %>');

app/views/comments/update.js.erb
$("#list_comments").html('<%= j render("shared/comments") %>');