config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do
    root "static_pages#home"

    devise_scope :user do
      get "/login", to: "devise/sessions#new", as: "login"
      post "/login", to: "devise/sessions#create"
      get "/register", to: "devise/registrations#new", as: "register"
      delete "/logout", to: "devise/sessions#destroy", as: "logout"
    end
    get "/search", to: "documents#search", as: "search"

    namespace :admin do
      resources :documents, only: %i(index edit update)
      resources :users, only: %i(index edit update) do
        collection do
          get "/export", to: "users#export"
          get "/export_status", to: "users#export_status"
          get "/export_download", to: "users#export_download"
        end
      end
      resources :categories, only: %i(index edit update new create)
      resources :histories, only: :index
    end

    resources :documents, only: %i(create show) do
        resources :comments, only: %i(new create delete)
    end
    resources :comments do
      resources :comments, only: %i(new create delete)
    end
    resources :downloads, only: :show
    resources :categories, only: %i(new create)
    resources :favorites, only: %i(create destroy)
    resources :account_activations, only: :edit
    devise_for :users
    resources :users, only: %i(show) do
      member do
        get :favorites
      end
    end
    authenticate :user, ->(user) { user.admin? } do
      mount Sidekiq::Web, at: "/sidekiq"
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  # constant
  enum status: {approved: 1, wait: 2, draft: 3, ban: 4, deleted: 5}

  # attr macro
  belongs_to :user
  belongs_to :category
  has_one_attached :doc
  has_many :comments
  has_many :histories
  has_many :favorites
  has_many :fav_users, through: :favorites, source: :user
  accepts_nested_attributes_for :category, reject_if: :reject_category
  delegate :fullname, to: :user, prefix: true, allow_nil: true
  delegate :size, to: :histories, prefix: true
  delegate :content_type, :previewable?, :preview, to: :doc, prefix: false
  ransack_alias :category, :category_name

  # validates
  validates :name, presence: true, length: {
    minimum: Settings.doc_min_length,
    maximum: Settings.doc_max_length
  }
  validates :doc, presence: true, content_type: {
    in: Settings.doc_type,
    message: I18n.t("error.invalid.doc_format")
  },
  size: {
    less_than: Settings.doc_size.megabytes,
    message:
      I18n.t("error.invalid.doc_size", size: Settings.doc_size.megabytes)
  }

  # scope
  scope :sort_by_created_at, ->{order created_at: :desc}
  scope :sort_by_name, ->{order :name}
  scope :search_by_name_or_cate, ->(search){
    left_outer_joins(:category).where("documents.name LIKE ?  OR categories.name LIKE ?", "%#{search}%", "%#{search}%") if search.present?
  }
  scope :find_in_month, ->{where "created_at BETWEEN ? AND ?", DateTime.now.beginning_of_month, DateTime.now.end_of_month}
  scope :find_in_year, ->{where "created_at BETWEEN ? AND ?", DateTime.now.beginning_of_year, DateTime.now.end_of_year}

  def reject_category attr
    attr[:name].blank?
  end
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < AdminController
  load_and_authorize_resource
  before_action :check_draft_doc, :check_change_status, :update_status_block, only: :update
  before_action :load_docs, only: :index

  def index
    @search = Document.search(params[:q])
    @documents = @search.result.not_draft.sort_by_created_at.paginate page: params[:page], per_page: Settings.per_page
  end

  def update
    check_approve
    load_docs
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def check_draft_doc
    return unless @document.draft?

    flash[:danger] = t "error.edit_draft_doc"
    redirect_to request.referer
  end

  def load_docs
    @documents = Document.not_draft.sort_by_created_at.paginate page: params[:page], per_page: Settings.per_page
  end

  def check_user_block
    ban_times = @document.user.documents.ban.size
    return if ban_times < Settings.times_upload_invalid || params[:document][:status] != Settings.status_ban

    @document.user.send_block_email if @document.user.block_user
  end

  def check_approve
    @document.user.send_upload_email(@document) if params[:document][:status] == Settings.status_approved
  end

  def check_change_status
    return if @document.status != params[:document][:status]

    flash[:warning] = t "warning.nothing_update"
    redirect_to request.referer
  end

  def update_status_block
    ActiveRecord::Base.transaction do
      @document.send("#{params[:document][:status]}!")
      check_user_block
    end
  rescue ActiveRecord::RecordInvalid => e
    render json: {
      error: e.to_s
    }, status: :not_found
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  load_and_authorize_resource param_method: :doc_params
  before_action :build_doc, :load_upload_times, only: :create

  def create
    if @document.save
      flash[:success] = t "success.doc_upload"
      current_user.add_coin Settings.coin_upload if @times < Settings.upload_times_in_month
      @document.category.send_create_cate_email if @flag_send_mail
    else
      flash[:danger] = t "error.doc_upload"
    end
    redirect_to root_url
  end

  def show; end

  def search
    @documents = Document.search_by_name_or_cate(params[:search]).approved.sort_by_name.paginate page: params[:page], per_page: Settings.per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def build_doc
    @document = current_user.documents.build(doc_params)
    @flag_send_mail = false
    if params[:document][:category_attributes][:name].present?
      @document.category_id = nil
      @document.category.user = current_user
      @flag_send_mail = true
    end
    @document.doc.attach(params[:document][:doc])
  end

  def doc_params
    params.require(:document).permit :name, :doc, :category_id, category_attributes: [:name, :parent_id]
  end

  def load_upload_times
    @times = current_user.documents.find_in_month.size
  end
end

app/views/documents/_document.html.erb
<li id="document-<%= document.id %>">
  <div class="row">
    <div class="col-sm">
      <div class="file-left">
        <% if document.previewable? %>
          <%= link_to(image_tag(document.preview(resize: "100x100>")), document) %>
        <% end %>
      </div>
      <div class="file-right">
        <h2 class="name"><%= document.name %></h2>
        <div class="file-info">
          <% if document.content_type == Settings.pdf_type %>
            <span class="view">
              <%= link_to document do%>
                <i class="fa fa-eye" aria-hidden="true"></i>
              <% end %>
            </span>
          <% end %>
          <span class="download">
            <%= link_to download_path(id: document.id), target: "_blank" do %>
              <i class="fa fa-download" aria-hidden="true"></i>
            <% end %>
          </span>
          <%= render "shared/favorite_form", doc: document %>
          <span class="author">
            <%= t "author", name: document.user_fullname %>
          </span>
          <span class="status">
            <%= t "status", status: document.status %>
          </span>
          <span class="download">
            <%= t "download_times", download: document.histories_size %>
          </span>
          <span class="timestamp">
            <% if can? :delete, document %>
              <%= link_to "#", method: :delete, data: {confirm: t("document.cfm")} do %>
                <i class="fas fa-trash"></i>
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/documents/search.js.erb
$('#list_doc').html('<%= j render "shared/list" %>');

app/views/documents/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2 class="center"><%= @document.name %></h2>
    <embed class="col-md-12" src="<%= polymorphic_url(@document.doc)%>" height="800" type="<%= Settings.pdf_type %>">
  </div>
</div>
<% if @document.approved? %>
  <h3><%= t("comment") %></h3>
  <%= form_for [@document, Comment.new] do |f| %>
    <%= f.text_area :content, placeholder: t("comment_placeholder") %><br/>
    <%= f.submit t("add_comment") %>
  <% end %>
  <div id = "list_comments">
    <%= render "shared/comments" %>
  </div>
<% end %>

<%= javascript_pack_tag "comment" %>